services:
  db:
    image: postgres:16.9
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV_LOCAL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE_LOCAL}
      DATABASE_HOST: ${DATABASE_HOST_LOCAL}
      DATABASE_USER: ${DATABASE_USER_LOCAL}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD_LOCAL}
      DATABASE_NAME: ${DATABASE_NAME_LOCAL}

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file: .env

volumes:
  pgdata:
